Repository team-thicket/thicket-main-repository, pull requests merged in 2023-11, with the labels that each got.

#1 init
  .gitignore
Labels: 오진석, 오류 수정

#10 Thicket#4
  thicket-member/src/main/java/com/example/thicketmember/HelloController.java
  thicket-member/src/main/java/com/example/thicketmember/Init.java
  thicket-member/src/main/java/com/example/thicketmember/ThicketMemberApplication.java
  thicket-member/src/main/java/com/example/thicketmember/TimeStamp.java
  thicket-member/src/main/java/com/example/thicketmember/controller/MemberApiController.java
  thicket-member/src/main/java/com/example/thicketmember/domain/Member.java
  thicket-member/src/main/java/com/example/thicketmember/dto/request/RequestInactiveDto.java
  thicket-member/src/main/java/com/example/thicketmember/dto/request/RequestSetNewPasswordDto.java
  thicket-member/src/main/java/com/example/thicketmember/dto/response/ResponseMemberDto.java
  thicket-member/src/main/java/com/example/thicketmember/enumerate/MemberStatus.java
  thicket-member/src/main/java/com/example/thicketmember/repository/MemberRepository.java
  thicket-member/src/main/java/com/example/thicketmember/service/MemberService.java
  thicket-member/src/main/java/com/example/thicketmember/service/MemberServiceImpl.java
  thicket-member/src/main/resources/application.yml
  thicket-member/src/test/java/com/example/thicketmember/service/MemberServiceImplTest.java
  thicket-member/src/test/resources/application.yml
Labels: 오진석, 이건주, 하은지, 구현 시작

#30 회원 기능 마무리(밸리데이션 추가, 컬럼어노테이션 추가 등)
  thicket-front/src/assets/css/setting/MemberMyPage.css
  thicket-front/src/member/component/Layout.jsx
  thicket-front/src/member/component/MemberMyPage.jsx
  thicket-front/src/member/pages/Mypage.jsx
  thicket-member/build.gradle
  thicket-member/src/main/java/com/example/thicketmember/Init.java
  thicket-member/src/main/java/com/example/thicketmember/config/SwaggerConfig.java
  thicket-member/src/main/java/com/example/thicketmember/controller/MemberApiController.java
  thicket-member/src/main/java/com/example/thicketmember/domain/Member.java
  thicket-member/src/main/java/com/example/thicketmember/dto/request/RequestAdminDto.java
  thicket-member/src/main/java/com/example/thicketmember/dto/request/RequestInactiveDto.java
  thicket-member/src/main/java/com/example/thicketmember/enumerate/Role.java
  thicket-member/src/main/java/com/example/thicketmember/service/MemberService.java
  thicket-member/src/main/java/com/example/thicketmember/service/MemberServiceImpl.java
  thicket-member/src/main/resources/application.yml
  thicket-member/src/test/java/com/example/thicketmember/service/MemberServiceImplTest.java
Labels: 이건주, 추가 구현

#33 (회원, 프론트) 회원 기능 마무리(api 연동)
  thicket-front/src/assets/css/setting/withdraw.css
  thicket-front/src/member/component/MemberMyPage.jsx
  thicket-front/src/member/component/Withdraw.jsx
  thicket-front/src/member/pages/Mypage.jsx
  thicket-member/src/main/java/com/example/thicketmember/controller/MemberApiController.java
  thicket-member/src/main/java/com/example/thicketmember/dto/request/RequestInactiveDto.java
  thicket-member/src/main/java/com/example/thicketmember/dto/request/RequestSetNewPasswordDto.java
  thicket-member/src/main/java/com/example/thicketmember/service/MemberServiceImpl.java
  thicket-member/src/main/resources/application.yml
  thicket-member/src/test/java/com/example/thicketmember/service/MemberServiceImplTest.java
Labels: 오진석, 추가 구현

#36 (결제) 프로젝트 세팅 및 기본 CRUD 구현 시작 #35
  thicket-payment/.gitignore
  thicket-payment/build.gradle
  thicket-payment/gradle/wrapper/gradle-wrapper.jar
  thicket-payment/gradle/wrapper/gradle-wrapper.properties
  thicket-payment/gradlew
  thicket-payment/gradlew.bat
  thicket-payment/settings.gradle
  thicket-payment/src/main/java/com/example/thicketpayment/Init.java
  thicket-payment/src/main/java/com/example/thicketpayment/ThicketPaymentApplication.java
  thicket-payment/src/main/java/com/example/thicketpayment/TimeStamp.java
  thicket-payment/src/main/java/com/example/thicketpayment/config/SwaggerConfig.java
  thicket-payment/src/main/java/com/example/thicketpayment/controller/AdminPaymentController.java
  thicket-payment/src/main/java/com/example/thicketpayment/controller/DepositPaymentController.java
  thicket-payment/src/main/java/com/example/thicketpayment/controller/FeignPaymentController.java
  thicket-payment/src/main/java/com/example/thicketpayment/controller/KakaoPaymentController.java
  thicket-payment/src/main/java/com/example/thicketpayment/controller/PaymentController.java
  thicket-payment/src/main/java/com/example/thicketpayment/domain/Payment.java
  thicket-payment/src/main/java/com/example/thicketpayment/dto/request/RequestCompletedPaymentDto.java
  thicket-payment/src/main/java/com/example/thicketpayment/dto/request/RequestExtendingOpenDateDto.java
  thicket-payment/src/main/java/com/example/thicketpayment/dto/request/RequestPaymentDto.java
  thicket-payment/src/main/java/com/example/thicketpayment/dto/response/ResponseCompletedPaymentDto.java
  thicket-payment/src/main/java/com/example/thicketpayment/dto/response/ResponsePaymentForMemberDto.java
  thicket-payment/src/main/java/com/example/thicketpayment/dto/response/ResponsePaymentForStageDto.java
  thicket-payment/src/main/java/com/example/thicketpayment/enumerate/HowReceive.java
  thicket-payment/src/main/java/com/example/thicketpayment/enumerate/Method.java
  thicket-payment/src/main/java/com/example/thicketpayment/enumerate/State.java
  thicket-payment/src/main/java/com/example/thicketpayment/repository/PaymentRepository.java
  thicket-payment/src/main/java/com/example/thicketpayment/service/PaymentService.java
  thicket-payment/src/main/java/com/example/thicketpayment/service/PaymentServiceImpl.java
  thicket-payment/src/main/resources/application.yml
  thicket-payment/src/test/java/com/example/thicketpayment/repository/PaymentRepositoryTest.java
  thicket-payment/src/test/java/com/example/thicketpayment/service/PaymentServiceTest.java
  thicket-payment/src/test/resources/application.yml
Labels: 오진석, 구현 시작, 결제(Payment)
