Repository team-thicket/thicket-main-repository, pull requests merged in 2023-12, with the labels that each got.

#53 Thicket#51
  thicket-front/package-lock.json
  thicket-front/package.json
  thicket-front/src/member/component/Layout.jsx
  thicket-front/src/member/pages/ApproveKakaopay.jsx
  thicket-front/src/member/pages/ReadyKakaopay.jsx
  thicket-ticket/src/main/java/com/example/thicketticket/controller/KakaoPaymentController.java
  thicket-ticket/src/main/java/com/example/thicketticket/dto/response/ResponseCompletedKakaopayDto.java
  thicket-ticket/src/main/java/com/example/thicketticket/service/KakaoPayServiceImpl.java
  thicket-ticket/src/main/resources/application.yml
Labels: 오진석, 추가 구현, 결제(Payment)

#56 공연(Stage) 프론트 추가 구현
  thicket-front/package-lock.json
  thicket-front/package.json
  thicket-front/src/member/component/AdminCreateStage.jsx
  thicket-front/src/member/component/Header.jsx
  thicket-front/src/member/pages/AdminPage.jsx
  thicket-front/src/member/pages/Main.jsx
  thicket-front/src/member/pages/Mypage.jsx
Labels: 이건주, 추가 구현, 공연(Stage)

#54 공연(Stage) 추가 구현
  thicket-stage/src/main/java/com/example/thicketstage/Init.java
  thicket-stage/src/main/java/com/example/thicketstage/TimeStamp.java
  thicket-stage/src/main/java/com/example/thicketstage/controller/StageController.java
  thicket-stage/src/main/java/com/example/thicketstage/controller/StageStartController.java
  thicket-stage/src/main/java/com/example/thicketstage/domain/Stage.java
  thicket-stage/src/main/java/com/example/thicketstage/domain/StageStart.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/request/RequestCreateStageDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/request/RequestCreateStageStartDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/request/RequestDeleteStageDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/request/RequestSetNewStatusDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/request/RequestStageStartUpdateDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/request/RequestUpdateInfoDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/response/ResponseStageDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/response/ResponseStageStartDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/response/ResponseStageThumbnailDto.java
  thicket-stage/src/main/java/com/example/thicketstage/enumerate/StageStatus.java
  thicket-stage/src/main/java/com/example/thicketstage/repository/StageRepository.java
  thicket-stage/src/main/java/com/example/thicketstage/repository/StageStartRepository.java
  thicket-stage/src/main/java/com/example/thicketstage/service/StageService.java
  thicket-stage/src/main/java/com/example/thicketstage/service/StageServiceImpl.java
  thicket-stage/src/main/java/com/example/thicketstage/service/StageStartService.java
  thicket-stage/src/main/java/com/example/thicketstage/service/StageStartServiceImpl.java
  thicket-stage/src/test/java/com/example/thicketstage/service/StageServiceImplTest.java
  thicket-stage/src/test/java/com/example/thicketstage/service/StageStartServiceImplTest.java
  thicket-stage/src/test/resources/application.yml
Labels: 하은지, 추가 구현, 공연(Stage)

#61 공연(Show) - 변경된 Entity 반영 후 코드 수정 + 공연(Show) 좌석(Chair) 병합 완료
  thicket-stage/build.gradle
  thicket-stage/src/main/java/com/example/thicketstage/Init.java
  thicket-stage/src/main/java/com/example/thicketstage/TimeStamp.java
  thicket-stage/src/main/java/com/example/thicketstage/config/SwaggerConfig.java
  thicket-stage/src/main/java/com/example/thicketstage/controller/ChairController.java
  thicket-stage/src/main/java/com/example/thicketstage/controller/StageController.java
  thicket-stage/src/main/java/com/example/thicketstage/controller/StageStartController.java
  thicket-stage/src/main/java/com/example/thicketstage/domain/Chair.java
  thicket-stage/src/main/java/com/example/thicketstage/domain/Stage.java
  thicket-stage/src/main/java/com/example/thicketstage/domain/StageStart.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/request/RequestCreateChairDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/request/RequestCreateStageDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/request/RequestCreateStageStartDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/request/RequestStageStartUpdateDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/request/RequestUpdateChairDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/request/RequestUpdateInfoDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/response/ResponseChairDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/response/ResponseStageDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/response/ResponseStageStartDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/response/ResponseStageThumbnailDto.java
  thicket-stage/src/main/java/com/example/thicketstage/repository/ChairRepository.java
  thicket-stage/src/main/java/com/example/thicketstage/service/ChairService.java
  thicket-stage/src/main/java/com/example/thicketstage/service/ChairServiceImpl.java
  thicket-stage/src/main/java/com/example/thicketstage/service/StageServiceImpl.java
  thicket-stage/src/main/java/com/example/thicketstage/service/StageStartService.java
  thicket-stage/src/main/java/com/example/thicketstage/service/StageStartServiceImpl.java
  thicket-stage/src/main/resources/application.yml
  thicket-stage/src/test/java/com/example/thicketstage/service/ChairServiceImplTest.java
  thicket-stage/src/test/java/com/example/thicketstage/service/StageServiceImplTest.java
  thicket-stage/src/test/java/com/example/thicketstage/service/StageStartServiceImplTest.java
Labels: 하은지, 추가 구현, 공연(Show) & 좌석(Chair)

#63 공연(Show) 프론트 현재 로그인한 관리자가 등록한 공연 목록
  thicket-front/src/assets/css/setting/MemberMyPage.css
  thicket-front/src/assets/css/setting/admin/DeleteSchedule.jsx
  thicket-front/src/assets/css/setting/admin/DeleteSeat.jsx
  thicket-front/src/assets/css/setting/admin/ImageFileHandling.jsx
  thicket-front/src/assets/css/setting/admin/RegistrationSchedule.jsx
  thicket-front/src/assets/css/setting/admin/RegistrationSeat.jsx
  thicket-front/src/assets/css/setting/admin/StylesOfCreate.jsx
  thicket-front/src/assets/css/setting/admin/StylesOfList.jsx
  thicket-front/src/member/component/AdminAllStageList.jsx
  thicket-front/src/member/component/AdminBeforeList.jsx
  thicket-front/src/member/component/AdminConcertList.jsx
  thicket-front/src/member/component/AdminCreateShow.jsx
  thicket-front/src/member/component/AdminCreateStage.jsx
  thicket-front/src/member/component/AdminEditShow.jsx
  thicket-front/src/member/component/AdminEndedList.jsx
  thicket-front/src/member/component/AdminMusicalList.jsx
  thicket-front/src/member/component/AdminOngoingList.jsx
  thicket-front/src/member/component/AdminPlayList.jsx
  thicket-front/src/member/component/MemberCouponList.jsx
  thicket-front/src/member/component/MemberMyPage.jsx
  thicket-front/src/member/component/MemberTicketingList.jsx
  thicket-front/src/member/component/MemberViewingList.jsx
  thicket-front/src/member/pages/AdminPage.jsx
  thicket-front/src/member/pages/Mypage.jsx
Labels: 이건주, 추가 구현, 공연(Show) & 좌석(Chair)

#65 Thicket#59
  thicket-auth/.gitignore
  thicket-auth/build.gradle
  thicket-auth/gradle/wrapper/gradle-wrapper.jar
  thicket-auth/gradle/wrapper/gradle-wrapper.properties
  thicket-auth/gradlew
  thicket-auth/gradlew.bat
  thicket-auth/settings.gradle
  thicket-auth/src/main/java/com/example/thicketauth/ThicketAuthApplication.java
  thicket-auth/src/main/java/com/example/thicketauth/smtp/config/redis/RedisConfig.java
  thicket-auth/src/main/java/com/example/thicketauth/smtp/config/security/SecurityConfig.java
  thicket-auth/src/main/java/com/example/thicketauth/smtp/controller/EmailController.java
  thicket-auth/src/main/java/com/example/thicketauth/smtp/domain/EmailMessage.java
  thicket-auth/src/main/java/com/example/thicketauth/smtp/domain/Member.java
  thicket-auth/src/main/java/com/example/thicketauth/smtp/dto/RequestVerificationDto.java
  thicket-auth/src/main/java/com/example/thicketauth/smtp/dto/ResponseEmailDto.java
  thicket-auth/src/main/java/com/example/thicketauth/smtp/service/EmailService.java
  thicket-auth/src/main/java/com/example/thicketauth/smtp/service/VerificationCodeService.java
  thicket-auth/src/main/resources/application.yml
  thicket-auth/src/test/java/com/example/thicketauth/ThicketAuthApplicationTests.java
  thicket-auth/src/test/java/resources/application.yml
  thicket-member/.gitignore
  thicket-member/build.gradle
  thicket-member/src/main/java/com/example/thicketmember/Init.java
  thicket-member/src/main/java/com/example/thicketmember/config/SecurityConfig.java
  thicket-member/src/main/java/com/example/thicketmember/controller/EmailApiController.java
  thicket-member/src/main/java/com/example/thicketmember/controller/MemberApiController.java
  thicket-member/src/main/java/com/example/thicketmember/controller/ValidationExceptionHandler.java
  thicket-member/src/main/java/com/example/thicketmember/domain/Member.java
  thicket-member/src/main/java/com/example/thicketmember/domain/Verification.java
  thicket-member/src/main/java/com/example/thicketmember/dto/request/RequestAdminDto.java
  thicket-member/src/main/java/com/example/thicketmember/dto/request/RequestChangeMemberRoleDto.java
  thicket-member/src/main/java/com/example/thicketmember/dto/request/RequestChangePasswordDto.java
  thicket-member/src/main/java/com/example/thicketmember/dto/request/RequestEmailDto.java
  thicket-member/src/main/java/com/example/thicketmember/dto/request/RequestMemberSigninDto.java
  thicket-member/src/main/java/com/example/thicketmember/dto/request/RequestMemberSignupDto.java
  thicket-member/src/main/java/com/example/thicketmember/dto/request/RequestVerificationDto.java
  thicket-member/src/main/java/com/example/thicketmember/dto/request/RequestWithdrawDto.java
  thicket-member/src/main/java/com/example/thicketmember/dto/response/ResponseMemberDto.java
  thicket-member/src/main/java/com/example/thicketmember/dto/response/ResponseMemberDtoForAdmin.java
  thicket-member/src/main/java/com/example/thicketmember/enumerate/MemberRole.java
  thicket-member/src/main/java/com/example/thicketmember/exception/ExpiredVerificationCodeException.java
  thicket-member/src/main/java/com/example/thicketmember/repository/MemberRepository.java
  thicket-member/src/main/java/com/example/thicketmember/repository/VerificationRepository.java
  thicket-member/src/main/java/com/example/thicketmember/service/EmailService.java
  thicket-member/src/main/java/com/example/thicketmember/service/EmailServiceImpl.java
  thicket-member/src/main/java/com/example/thicketmember/service/MemberService.java
  thicket-member/src/main/java/com/example/thicketmember/service/MemberServiceImpl.java
  thicket-member/src/main/resources/application.yml
  thicket-member/src/main/resources/templates/email.html
  thicket-member/src/test/java/com/example/thicketmember/service/EmailServiceImplTest.java
  thicket-member/src/test/java/com/example/thicketmember/service/MemberServiceImplTest.java
  thicket-member/src/test/resources/application.yml
  thicket-ticket/src/main/java/com/example/thicketticket/controller/TicketController.java
Labels: 오진석, 오류 수정, 추가 구현, 회원(Member) & 인증/인가(Certify)

#68 공연(Show) 추가 기능 구현 및 수정
  thicket-stage/src/main/java/com/example/thicketstage/Init.java
  thicket-stage/src/main/java/com/example/thicketstage/controller/ChairController.java
  thicket-stage/src/main/java/com/example/thicketstage/controller/StageController.java
  thicket-stage/src/main/java/com/example/thicketstage/controller/StageStartController.java
  thicket-stage/src/main/java/com/example/thicketstage/domain/Chair.java
  thicket-stage/src/main/java/com/example/thicketstage/domain/Stage.java
  thicket-stage/src/main/java/com/example/thicketstage/domain/StageStart.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/request/RequestCreateStageDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/request/RequestSetNewStatusDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/response/ResponseChairDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/response/ResponseStageDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/response/ResponseStageThumbnailDto.java
  thicket-stage/src/main/java/com/example/thicketstage/repository/ChairRepository.java
  thicket-stage/src/main/java/com/example/thicketstage/repository/StageRepository.java
  thicket-stage/src/main/java/com/example/thicketstage/repository/StageStartRepository.java
  thicket-stage/src/main/java/com/example/thicketstage/service/ChairService.java
  thicket-stage/src/main/java/com/example/thicketstage/service/ChairServiceImpl.java
  thicket-stage/src/main/java/com/example/thicketstage/service/StageService.java
  thicket-stage/src/main/java/com/example/thicketstage/service/StageServiceImpl.java
  thicket-stage/src/main/java/com/example/thicketstage/service/StageStartService.java
  thicket-stage/src/main/java/com/example/thicketstage/service/StageStartServiceImpl.java
  thicket-stage/src/main/resources/application.yml
  thicket-stage/src/test/java/com/example/thicketstage/service/StageServiceImplTest.java
Labels: 하은지, 오류 수정, 추가 구현, 공연(Show) & 좌석(Chair)

#70 공연(Show) - 프론트 등록한 공연 수정
  thicket-front/.idea/misc.xml
  thicket-front/package-lock.json
  thicket-front/package.json
  thicket-front/src/assets/css/setting/MainStyleCSS.jsx
  thicket-front/src/assets/css/setting/admin/StylesOfCreate.jsx
  thicket-front/src/assets/css/setting/admin/StylesOfList.jsx
  thicket-front/src/member/component/AdminCreateShow.jsx
  thicket-front/src/member/component/Header.jsx
  thicket-front/src/member/component/Layout.jsx
  thicket-front/src/member/component/MemberMyPage.jsx
  thicket-front/src/member/component/Menu.jsx
  thicket-front/src/member/component/Nav.jsx
  thicket-front/src/member/pages/AdminPage.jsx
  thicket-front/src/member/pages/AuthPage.jsx
  thicket-front/src/member/pages/Login.jsx
  thicket-front/src/member/pages/Main.jsx
  thicket-front/src/member/pages/MainAllList.jsx
  thicket-front/src/member/pages/MainConcertList.jsx
  thicket-front/src/member/pages/MainMusicalList.jsx
  thicket-front/src/member/pages/MainOpeningSoon.jsx
  thicket-front/src/member/pages/MainPlayList.jsx
  thicket-front/src/member/pages/MyPage.jsx
  thicket-front/src/member/pages/Mypage.jsx
  thicket-front/src/member/pages/ShowDetailPage.jsx
  thicket-front/src/member/pages/SignUp.jsx
  thicket-member/src/main/java/com/example/thicketmember/ThicketMemberApplication.java
  thicket-member/src/main/java/com/example/thicketmember/controller/EmailApiController.java
  thicket-member/src/main/java/com/example/thicketmember/controller/MemberApiController.java
Labels: 이건주, 추가 구현, 프론트

#72 공연(Show) - 관리자 기능 분리
  thicket-stage/src/main/java/com/example/thicketstage/controller/ChairController.java
  thicket-stage/src/main/java/com/example/thicketstage/controller/StageController.java
  thicket-stage/src/main/java/com/example/thicketstage/controller/StageStartController.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/request/RequestCreateStageDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/request/RequestUpdateChairDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/response/ResponseAdminStageDto.java
  thicket-stage/src/main/java/com/example/thicketstage/exception/CustomExceptionHandler.java
  thicket-stage/src/main/java/com/example/thicketstage/exception/ErrorResponse.java
  thicket-stage/src/main/java/com/example/thicketstage/service/ChairService.java
  thicket-stage/src/main/java/com/example/thicketstage/service/ChairServiceImpl.java
  thicket-stage/src/main/java/com/example/thicketstage/service/StageService.java
  thicket-stage/src/main/java/com/example/thicketstage/service/StageServiceImpl.java
  thicket-stage/src/main/java/com/example/thicketstage/service/StageStartServiceImpl.java
  thicket-stage/src/test/java/com/example/thicketstage/service/StageServiceImplTest.java
Labels: 하은지, 공연(Show) & 좌석(Chair)

#76 프론트 메인페이지 연동
  thicket-front/src/assets/css/setting/MainStyleCSS.jsx
  thicket-front/src/member/pages/MainAllList.jsx
  thicket-front/src/member/pages/MainConcertList.jsx
  thicket-front/src/member/pages/MainMusicalList.jsx
  thicket-front/src/member/pages/MainOpeningSoon.jsx
  thicket-front/src/member/pages/MainPlayList.jsx
  thicket-stage/src/main/java/com/example/thicketstage/dto/response/ResponseAdminStageDto.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/response/ResponseStageThumbnailDto.java
  thicket-stage/src/main/resources/application.yml
Labels: 이건주, 추가 구현, 프론트

#78 공연(Show) - member
  thicket-auth/.gradle/8.4/checksums/checksums.lock
  thicket-auth/.gradle/8.4/checksums/md5-checksums.bin
  thicket-auth/.gradle/8.4/checksums/sha1-checksums.bin
  thicket-auth/.gradle/8.4/dependencies-accessors/dependencies-accessors.lock
  thicket-auth/.gradle/8.4/dependencies-accessors/gc.properties
  thicket-auth/.gradle/8.4/executionHistory/executionHistory.bin
  thicket-auth/.gradle/8.4/executionHistory/executionHistory.lock
  thicket-auth/.gradle/8.4/fileChanges/last-build.bin
  thicket-auth/.gradle/8.4/fileHashes/fileHashes.bin
  thicket-auth/.gradle/8.4/fileHashes/fileHashes.lock
  thicket-auth/.gradle/8.4/fileHashes/resourceHashesCache.bin
  thicket-auth/.gradle/8.4/gc.properties
  thicket-auth/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  thicket-auth/.gradle/buildOutputCleanup/cache.properties
  thicket-auth/.gradle/buildOutputCleanup/outputFiles.bin
  thicket-auth/.gradle/file-system.probe
  thicket-auth/.gradle/vcs-1/gc.properties
  thicket-auth/build/classes/java/main/com/example/thicketauth/ThicketAuthApplication.class
  thicket-auth/build/classes/java/main/com/example/thicketauth/smtp/config/redis/RedisConfig.class
  thicket-auth/build/classes/java/main/com/example/thicketauth/smtp/config/security/SecurityConfig.class
  thicket-auth/build/classes/java/main/com/example/thicketauth/smtp/controller/EmailController.class
  thicket-auth/build/classes/java/main/com/example/thicketauth/smtp/domain/EmailMessage$EmailMessageBuilder.class
  thicket-auth/build/classes/java/main/com/example/thicketauth/smtp/domain/EmailMessage.class
  thicket-auth/build/classes/java/main/com/example/thicketauth/smtp/domain/Member.class
  thicket-auth/build/classes/java/main/com/example/thicketauth/smtp/dto/RequestEmailDto.class
  thicket-auth/build/classes/java/main/com/example/thicketauth/smtp/dto/RequestVerificationDto.class
  thicket-auth/build/classes/java/main/com/example/thicketauth/smtp/dto/ResponseEmailDto.class
  thicket-auth/build/classes/java/main/com/example/thicketauth/smtp/service/EmailService.class
  thicket-auth/build/classes/java/main/com/example/thicketauth/smtp/service/VerificationCodeService.class
  thicket-auth/build/resources/main/application.yml
  thicket-auth/build/resources/main/templates/email.html
  thicket-auth/build/tmp/compileJava/previous-compilation-data.bin
  thicket-front/.idea/misc.xml
  thicket-front/src/member/pages/ShowDetailPage.jsx
  thicket-front/src/payment/pages/Reservation.jsx
  thicket-payment/.gradle/8.4/checksums/checksums.lock
  thicket-payment/.gradle/8.4/dependencies-accessors/dependencies-accessors.lock
  thicket-payment/.gradle/8.4/dependencies-accessors/gc.properties
  thicket-payment/.gradle/8.4/executionHistory/executionHistory.lock
  thicket-payment/.gradle/8.4/fileChanges/last-build.bin
  thicket-payment/.gradle/8.4/fileHashes/fileHashes.lock
  thicket-payment/.gradle/8.4/gc.properties
  thicket-payment/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  thicket-payment/.gradle/buildOutputCleanup/cache.properties
  thicket-payment/.gradle/vcs-1/gc.properties
  thicket-stage/src/main/java/com/example/thicketstage/dto/response/ResponseAdminStageDto.java
Labels: 하은지, 공연(Show) & 좌석(Chair)

#80 인증/인가(Certify) 시큐리티 및 JWT 코드 정리 및 재구현
  thicket-eureka-server/src/main/java/com/example/thicketeurekaserver/ThicketEurekaServerApplication.java
  thicket-eureka-server/src/main/resources/application.properties
  thicket-eureka-server/src/main/resources/application.yml
  thicket-gateway/.gitignore
  thicket-gateway/build.gradle
  thicket-gateway/src/main/java/com/example/thicketgateway/ThicketGatewayApplication.java
  thicket-gateway/src/main/java/com/example/thicketgateway/config/SecurityConfig.java
  thicket-gateway/src/main/java/com/example/thicketgateway/filter/GlobalFilter.java
  thicket-gateway/src/main/java/com/example/thicketgateway/jwt/JwtAuthenticationConverter.java
  thicket-gateway/src/main/java/com/example/thicketgateway/jwt/JwtDecoder.java
  thicket-gateway/src/main/java/com/example/thicketgateway/jwt/JwtDecoderImpl.java
  thicket-gateway/src/main/java/com/example/thicketgateway/jwt/JwtReactiveAuthenticationManager.java
  thicket-gateway/src/main/resources/application.properties
  thicket-gateway/src/main/resources/application.yml
  thicket-member/.gitignore
  thicket-member/build.gradle
  thicket-member/src/main/java/com/example/thicketmember/Init.java
  thicket-member/src/main/java/com/example/thicketmember/ThicketMemberApplication.java
  thicket-member/src/main/java/com/example/thicketmember/config/SecurityConfig.java
  thicket-member/src/main/java/com/example/thicketmember/controller/MemberApiController.java
  thicket-member/src/main/java/com/example/thicketmember/domain/Member.java
  thicket-member/src/main/java/com/example/thicketmember/dto/request/RequestChangeMemberRoleDto.java
  thicket-member/src/main/java/com/example/thicketmember/dto/response/ResponseMemberDtoForAdmin.java
  thicket-member/src/main/java/com/example/thicketmember/enumerate/MemberRole.java
  thicket-member/src/main/java/com/example/thicketmember/service/MemberService.java
  thicket-member/src/main/java/com/example/thicketmember/service/MemberServiceImpl.java
  thicket-member/src/main/java/com/example/thicketmember/util/JwtTokenGenerator.java
  thicket-member/src/main/java/com/example/thicketmember/util/PasswordUtil.java
  thicket-member/src/main/java/com/example/thicketmember/util/config/SwaggerConfig.java
  thicket-member/src/main/resources/application.yml
  thicket-member/src/test/java/com/example/thicketmember/service/MemberServiceImplTest.java
  thicket-member/src/test/resources/secretKey.properties
Labels: 오진석, 오류 수정, 추가 구현, 회원(Member) & 인증/인가(Certify)

#82 프론트 공연디테일페이지 연동
  thicket-front/src/assets/css/setting/MainStyleCSS.jsx
  thicket-front/src/member/pages/MainAllList.jsx
  thicket-front/src/member/pages/MainConcertList.jsx
  thicket-front/src/member/pages/MainMusicalList.jsx
  thicket-front/src/member/pages/MainOpeningSoon.jsx
  thicket-front/src/member/pages/MainPlayList.jsx
  thicket-front/src/member/pages/ShowDetailPage.jsx
  thicket-stage/src/main/resources/application.yml
Labels: 이건주, 추가 구현, 프론트

#86 공연(Show) SSE 예매 시작 버튼 활성화 구현
  thicket-stage/src/main/java/com/example/thicketstage/Init.java
  thicket-stage/src/main/java/com/example/thicketstage/ThicketStageApplication.java
  thicket-stage/src/main/java/com/example/thicketstage/TimeStamp.java
  thicket-stage/src/main/java/com/example/thicketstage/controller/StageController.java
  thicket-stage/src/main/java/com/example/thicketstage/domain/Chair.java
  thicket-stage/src/main/java/com/example/thicketstage/dto/response/ResponseStageThumbnailDto.java
  thicket-stage/src/main/java/com/example/thicketstage/exception/CustomExceptionHandler.java
  thicket-stage/src/main/java/com/example/thicketstage/exception/ServerConnectionOutException.java
  thicket-stage/src/main/java/com/example/thicketstage/repository/StageRepository.java
  thicket-stage/src/main/java/com/example/thicketstage/service/StageService.java
  thicket-stage/src/main/java/com/example/thicketstage/service/StageServiceImpl.java
  thicket-stage/src/main/java/com/example/thicketstage/util/SseEmitters.java
  thicket-stage/src/main/resources/application.yml
Labels: 오진석, 오류 수정, 추가 구현, 공연(Show) & 회차정보(Ticket)

#96 프론트 예약 -> 결제
  thicket-front/package-lock.json
  thicket-front/package.json
  thicket-front/src/member/pages/MainPlayList.jsx
  thicket-front/src/member/pages/ShowDetailPage.jsx
  thicket-front/src/payment/component/Bank.jsx
  thicket-front/src/payment/component/Dropdown.jsx
  thicket-front/src/payment/component/UseDetectClose.jsx
  thicket-front/src/payment/pages/Payment.jsx
  thicket-front/src/payment/pages/Reservation.jsx
Labels: 하은지, 구현 시작, 프론트

#103 프론트 메인페이지→디테일페이 연동 구현 및 기타작업
  thicket-front/src/assets/css/setting/MainStyleCSS.jsx
  thicket-front/src/assets/css/setting/admin/StylesOfCreate.jsx
  thicket-front/src/assets/css/setting/admin/StylesOfList.jsx
  thicket-front/src/member/component/MemberTicketingList.jsx
  thicket-front/src/member/component/MemberViewingList.jsx
  thicket-front/src/member/pages/MainOpeningSoon.jsx
  thicket-front/src/member/pages/ShowDetailPage.jsx
  thicket-front/src/payment/pages/Cancel.jsx
  thicket-front/src/payment/pages/Cancel2.jsx
  thicket-front/src/payment/pages/Cancel3.jsx
Labels: 이건주, 추가 구현, 프론트

#106 프론트 예약 -> 결제 화면 추가구현
  thicket-front/src/member/component/Header.jsx
  thicket-front/src/member/pages/ReadyKakaopay.jsx
  thicket-front/src/member/pages/ShowDetailPage.jsx
  thicket-front/src/payment/component/Bank.jsx
  thicket-front/src/payment/component/Dropdown.jsx
  thicket-front/src/payment/pages/Payment.jsx
  thicket-front/src/payment/pages/Reservation.jsx
  thicket-gateway/.gitignore
  thicket-member/.gitignore
  thicket-member/src/test/resources/secretKey.properties
  thicket-stage/.gitignore
  thicket-ticket/build.gradle
  thicket-ticket/src/main/java/com/example/thicketticket/service/TicketServiceImpl.java
  thicket-ticket/src/main/resources/application.yml
Labels: 하은지, 프론트

#110 (예매) 타임스탬프수정,예매 테스트정상작동확인
  thicket-loader/src/main/java/com/example/thicketloader/service/Service.java
  thicket-loader/src/main/java/com/example/thicketloader/service/TicketService.java
  thicket-ticket/build.gradle
  thicket-ticket/src/main/java/com/example/thicketticket/domain/Ticket.java
  thicket-ticket/src/main/java/com/example/thicketticket/dto/request/RequestCreateTicketDto.java
  thicket-ticket/src/main/java/com/example/thicketticket/service/TicketServiceImpl.java
Labels: 오강석, 추가 구현, 예매(Ticket) & 결제(Payment)

#112 프론트 마이페이지 추가 구현
  thicket-front/src/member/component/Header.jsx
  thicket-front/src/member/component/MemberTicketingList.jsx
  thicket-front/src/member/component/MemberViewingList.jsx
  thicket-front/src/member/pages/MainPlayList.jsx
  thicket-front/src/member/pages/ShowDetailPage.jsx
  thicket-front/src/payment/pages/Cancel.jsx
  thicket-front/src/payment/pages/Cancel2.jsx
  thicket-front/src/payment/pages/Cancel3.jsx
  thicket-ticket/src/main/java/com/example/thicketticket/controller/TicketController.java
Labels: 이건주, 추가 구현, 프론트

#111 CSS 전체 수정 들어가겠읍니다. -> 메인화면 로그인 화면 수정
  thicket-front/src/assets/css/setting/MainStyleCSS.jsx
  thicket-front/src/member/component/Header.jsx
  thicket-front/src/member/component/HeaderMenu.jsx
  thicket-front/src/member/pages/Login.jsx
  thicket-front/src/member/pages/SignUp.jsx
Labels: 하은지, 프론트

#117 프론트 공연정보 페이지 달력 디테일 작업
  thicket-front/src/member/component/MemberTicketingList.jsx
  thicket-front/src/member/pages/ShowDetailPage.jsx
  thicket-front/src/payment/pages/Cancel.jsx
  thicket-front/src/payment/pages/Cancel2.jsx
  thicket-front/src/payment/pages/Cancel3.jsx
Labels: 이건주, 추가 구현, 프론트

#118 CSS 전체 수정 들어가겠읍니다.
  thicket-front/src/assets/css/setting/MainStyleCSS.jsx
  thicket-front/src/assets/css/setting/admin/StylesOfCreate.jsx
  thicket-front/src/member/component/AdminAllStageList.jsx
  thicket-front/src/member/component/AdminBeforeList.jsx
  thicket-front/src/member/component/AdminCreateShow.jsx
  thicket-front/src/member/component/HeaderMenu.jsx
  thicket-front/src/member/component/Layout.jsx
  thicket-front/src/member/component/MemberMyPage.jsx
  thicket-front/src/member/component/MemberTicketingList.jsx
  thicket-front/src/member/component/Menu.jsx
  thicket-front/src/member/component/Withdraw.jsx
  thicket-front/src/member/pages/AdminPage.jsx
  thicket-front/src/member/pages/AuthPage.jsx
  thicket-front/src/member/pages/Login.jsx
  thicket-front/src/member/pages/MainAllList.jsx
  thicket-front/src/member/pages/MainConcertList.jsx
  thicket-front/src/member/pages/MainMusicalList.jsx
  thicket-front/src/member/pages/MainOpeningSoon.jsx
  thicket-front/src/member/pages/MainPlayList.jsx
  thicket-front/src/member/pages/MainSearchList.jsx
  thicket-front/src/member/pages/MyPage.jsx
  thicket-front/src/member/pages/ShowDetailPage.jsx
  thicket-front/src/member/pages/SignUp.jsx
  thicket-front/src/payment/component/UseDetectClose.jsx
  thicket-stage/src/main/java/com/example/thicketstage/Init.java
  thicket-stage/src/main/java/com/example/thicketstage/service/StageServiceImpl.java
  thicket-ticket/src/main/resources/application.yml
Labels: 하은지, 추가 구현, 프론트

#127 2023-12-29, 스테이지 인잇 변경, 시간 오름차순 정렬, 찐막커밋
  thicket-front/src/member/pages/ShowDetailPage.jsx
  thicket-stage/src/main/java/com/example/thicketstage/Init.java
Labels: 이건주, 추가 구현, 프론트
